### ISSUE TITLE
I got error when load a class SteamWebApi

### ISSUE THREAD

**Issue by ThreadShakur** [DrBomb/python-steamcommunity#8]
def get_trades(Login):
    wapi = SteamWebApi.SteamWebApi(Login,key="F473D231ED3D0B2F58FDA5B1EE8844CF")
    tapi = SteamWebApi.IEconService(wapi)

```
print(tapi.GetTradeOffers())
```

Login.login(details)
get_trades(Login)

I got error AssertionError: Login is not a SteamLogin instance
When i print Login python give me that Login have object SteamLogin and SteamWebApi

**Comment by DrBomb** [comment]
your Login must be failing somewhere, or you're doing something wrong

**Comment by ThreadShakur** [comment]
```
def get_trades(Login):
    wapi = SteamWebApi.SteamWebApi(Login,key="F473D231ED3D0B2F58FDA5B1EE8844CF")
    tapi = SteamWebApi.IEconService(wapi)

    print(tapi.GetTradeOffers())

# LOGIN
Login = SteamLogin.SteamLogin()

offset = SteamMobileAuth.getTimeOffset()
while True:
    try:
        Login.login(details)
        get_trades(Login)
        break
    except SteamLogin.TwoFactorCodeRequiredException:
        details['twoFactorCode'] = SteamMobileAuth.generateAuthCode(details['shared_secret'],offset)
    except SteamLogin.CaptchaRequiredException as e:
        print(e)
        details['captcha'] = raw_input()
    except SteamLogin.EmailAuthException as e:
        print(e)
    except SteamLogin.TooManyRequestsException as e:
        print("Retrying after " + e.retryafter+5 + " seconds")
        time.sleep(e.retryafter+5)
```

it's code of login

**Comment by DrBomb** [comment]
``` python
offset = SteamMobileAuth.getTimeOffset()
while True:
  try:
    Login.login(details)
    get_trades(Login) < THIS
    break
...
```

Remove that line, do the rest after the code logs in successfully

**Comment by ThreadShakur** [comment]
Ok.. how to login with pickle? How to get SteamLogin object from logs in pickle?

**Comment by KowalskiThomas** [comment]
In the only example, you have something that tries to load the session from login.pickle. To load the object you just do pickle.load(file), and it returns you an object of the good type.

**Comment by ThreadShakur** [comment]
When i load my func with pickle i got same error

Code

```
 def get_trades(Login):
    wapi = SteamWebApi.SteamWebApi(Login,key="F473D231ED3D0B2F58FDA5B1EE8844CF")
    tapi = SteamWebApi.IEconService(wapi)

    print(tapi.GetTradeOffers())

# LOGIN
try:
    with open("Login.pickle") as f:
        Login = pickle.load(f)
        get_trades(Login)
except IOError:
    Login = SteamLogin.SteamLogin()

    offset = SteamMobileAuth.getTimeOffset()
    while True:
        try:
            Login.login(details)
            break
        except SteamLogin.TwoFactorCodeRequiredException:
            details['twoFactorCode'] = SteamMobileAuth.generateAuthCode(details['shared_secret'],offset)
        except SteamLogin.CaptchaRequiredException as e:
            print(e)
            details['captcha'] = raw_input()
        except SteamLogin.EmailAuthException as e:
            print(e)
        except SteamLogin.TooManyRequestsException as e:
            print("Retrying after " + e.retryafter+5 + " seconds")
            time.sleep(e.retryafter+5)
    with open("Login.pickle",'wb') as f:
        pickle.dump(Login,f)
```

Error

`SteamLogin.SteamLogin object at 0x7f93a2d841d0
SteamWebApi.SteamWebApi object at 0x7f93a2d84310
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    get_trades(Login)
  File "main.py", line 12, in get_trades
    tapi = SteamWebApi.IEconService(wapi)
  File "/home/vadim/Документы/python/SteamWebApi.py", line 7, in __init__
    assert isinstance(Login, SteamLogin.SteamLogin), "Login is not a SteamLogin instance"
AssertionError: Login is not a SteamLogin instance
`

**Comment by KowalskiThomas** [comment]
I don't even see where you call your function.

**Comment by ThreadShakur** [comment]
get_trades(Login) my function

**Comment by KowalskiThomas** [comment]
Why don't you put the get_trades after all the "login" block ?

**Comment by ThreadShakur** [comment]
#Error...

```
def get_trades(Login):
    wapi = SteamWebApi.SteamWebApi(Login,key="F473D231ED3D0B2F58FDA5B1EE8844CF")
    tapi = SteamWebApi.IEconService(wapi)

    print(tapi.GetTradeOffers())

# LOGIN
try:
    with open("Login.pickle") as f:
        Login = pickle.load(f)
except IOError:
    Login = SteamLogin.SteamLogin()

    offset = SteamMobileAuth.getTimeOffset()
    while True:
        try:
            Login.login(details)
            break
        except SteamLogin.TwoFactorCodeRequiredException:
            details['twoFactorCode'] = SteamMobileAuth.generateAuthCode(details['shared_secret'],offset)
        except SteamLogin.CaptchaRequiredException as e:
            print(e)
            details['captcha'] = raw_input()
        except SteamLogin.EmailAuthException as e:
            print(e)
        except SteamLogin.TooManyRequestsException as e:
            print("Retrying after " + e.retryafter+5 + " seconds")
            time.sleep(e.retryafter+5)
    with open("Login.pickle",'wb') as f:
        pickle.dump(Login,f)


get_trades(Login)   
```

**Comment by DrBomb** [comment]
check that the Login object is being created properly

**Comment by ThreadShakur** [comment]
when i print Login i have that:

```
SteamLogin.SteamLogin object at 0x7f93a2d841d0 
SteamWebApi.SteamWebApi object at 0x7f93a2d84310
```

**Comment by ThreadShakur** [comment]
I know why it not works... It was because i call SteamWebApi in 2 times

With error:

```
    wapi = SteamWebApi.SteamWebApi(Login,key="F473D231ED3D0B2F58FDA5B1EE8844CF")
    tapi = SteamWebApi.IEconService(wapi)
```

Without error:

`tapi = IEconService(login,key=details['api_key'])`

**Comment by DrBomb** [comment]
Just read the source code, I'll be closing this one too
